apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buildspecifications.ocibuilder
spec:
  group: ocibuilder
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: BuildSpecification
    singular: buildspecification
    plural: buildspecifications
    listKind: BuildSpecificationList
    shortNames:
      - bs
